M48
; DRILL file KiCad 10.0.2 date 2026-09-28T15:33:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T15:33:11+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X82.17Y-73.35
X90.33Y-146.91
X275.0Y-145.0
X277.87Y-72.51
T2
X115.0Y-116.085
X115.0Y-146.085
X180.0Y-116.085
X180.0Y-146.085
T3
X91.62Y-80.7
X91.62Y-93.4
M30
