from pathlib import Path
import json,pcbnew as p,subprocess,shutil
D=Path('KiCad-RevE');E=Path('engineering');f=D/'reports/amp-ground-pin-widths.json';r=json.loads(f.read_text());widths={'bf6ade44-d1c7-46a7-bda9-f078665f32f7':.35,'b2117fb3-8b73-4730-857f-57adee7071de':.35,'fa20c80a-0752-4bb1-946f-ad6e4b077f9a':.25,'8bf84c89-c5b6-493c-9b0b-70c88506c79b':.35};b=p.LoadBoard(str(D/'power-trial.kicad_pcb'))
for t in b.GetTracks():
 uid=t.m_Uuid.AsString()
 if uid in widths:t.SetWidth(p.FromMM(widths[uid]))
for row in r['changes']:
 if row['uuid'] in widths:row['new_width_mm']=widths[row['uuid']]
p.ZONE_FILLER(b).Fill(b.Zones());p.SaveBoard(str(D/'power-trial.kicad_pcb'),b)
subprocess.run([r'C:\Program Files\KiCad\10.0\bin\kicad-cli.exe','pcb','drc','--format','json','-o',str(D/'reports/power-trial-drc.json'),str(D/'power-trial.kicad_pcb')],check=True);d=json.loads((D/'reports/power-trial-drc.json').read_text());assert not d['violations'] and not d['unconnected_items'];r.update(status='accepted',limitation='Direct pin segments only; some are tiny imported stubs. Downstream ground paths, filled-plane continuity and return impedance are not qualified by this change.');f.write_text(json.dumps(r,indent=2));backup=D/'before-amp-ground-pin-widths.kicad_pcb';assert not backup.exists();shutil.copy2(D/'PoE-Speaker-RevE.kicad_pcb',backup);shutil.copy2(D/'power-trial.kicad_pcb',D/'PoE-Speaker-RevE.kicad_pcb')
with (E/'REVE-TRUNK-ROUTING.md').open('a',encoding='utf-8') as out:out.write('\n\n## Accepted amplifier ground-pin track widths — 2026-09-14\n\nWidened 21 directly connected U5 GND segments from 0.2 mm: seventeen to 0.4 mm, three to 0.35 mm, one to 0.25 mm. This count includes tiny imported pin stubs; it does not represent 21 independent return paths. Four full-width candidates conflicted with MUTE/SW_POS/SDZ/GAIN vias and were reduced to preserve clearance. Zero final DRC and unconnected findings. No route or via relocation. Full UUIDs/dimensions in reports/amp-ground-pin-widths.json. Backup before-amp-ground-pin-widths.kicad_pcb. Remaining: ground pin-to-plane access and return continuity, including downstream 0.2 mm tracks.\n')
f=E/'package_prototype_review.py';s=f.read_text().replace('Next: verify amplifier ground-pin access and ground-plane continuity.', 'Next: verify downstream amplifier ground-pin-to-plane paths and ground-plane continuity. Twenty-one direct ground-pin track segments were widened to 0.25-0.4 mm with clean DRC; this includes tiny stubs and does not qualify complete ground returns (reports/amp-ground-pin-widths.json).');f.write_text(s)
