from pathlib import Path
import json,pcbnew as p,subprocess,shutil
D=Path('KiCad-RevE');E=Path('engineering');f=D/'reports/power-via-review.json';r=json.loads(f.read_text());uid='b983fee9-a187-486f-966c-0b0f0547dc19';row=next(x for x in r['vias'] if x['uuid']==uid);b=p.LoadBoard(str(D/'power-trial.kicad_pcb'))
for v in b.GetTracks():
 if v.m_Uuid.AsString()==uid:v.SetWidth(p.FromMM(row['old_diameter_mm']));v.SetDrill(p.FromMM(row['old_drill_mm']))
row.update(final_diameter_mm=row['old_diameter_mm'],final_drill_mm=row['old_drill_mm'],changed=False,reason='Retained original: adjacent EFUSE_PGTH copper clearance');p.ZONE_FILLER(b).Fill(b.Zones());p.SaveBoard(str(D/'power-trial.kicad_pcb'),b)
subprocess.run([r'C:\Program Files\KiCad\10.0\bin\kicad-cli.exe','pcb','drc','--format','json','-o',str(D/'reports/power-trial-drc.json'),str(D/'power-trial.kicad_pcb')],check=True);d=json.loads((D/'reports/power-trial-drc.json').read_text());assert not d['violations'] and not d['unconnected_items'];r['validation']={'drc_findings':0,'unconnected_items':0,'changed_vias':sum(x['changed'] for x in r['vias'])};f.write_text(json.dumps(r,indent=2))
backup=D/'before-load-via-enlargement.kicad_pcb';assert not backup.exists();shutil.copy2(D/'PoE-Speaker-RevE.kicad_pcb',backup);shutil.copy2(D/'power-trial.kicad_pcb',D/'PoE-Speaker-RevE.kicad_pcb')
with (E/'REVE-TRUNK-ROUTING.md').open('a',encoding='utf-8') as out:out.write('\n\n## Accepted power-via enlargement — 2026-09-14\n\nReviewed 18 audited load-path vias with 0.3 mm drills. Eleven now use larger copper/drill geometry (1.0/0.5 mm or 0.8/0.4 mm); seven retain original geometry because of neighboring copper. Full per-via positions, UUIDs and before/after dimensions: reports/power-via-review.json. Proposed drills were screened against all component pad bounding boxes with 0.35 mm margin to avoid moving holes into solder pads. Final filled-board DRC zero, unconnected zero. Original board preserved in before-load-via-enlargement.kicad_pcb. This is a geometry improvement, not a current rating: plating thickness, thermal behavior and ground-return review remain pending.\n')
f=E/'package_prototype_review.py';s=f.read_text();s=s.replace('Next: review load-path vias and amplifier supply/ground returns.', 'Next: review the seven remaining constrained load-path vias and amplifier supply/ground returns. Eleven load-path vias have accepted larger drills/copper pads; see reports/power-via-review.json. Via current ratings still require plating and stackup assumptions.');f.write_text(s)
