from pathlib import Path
import pcbnew as p,json,shutil
D=Path('KiCad-RevE');E=Path('engineering');b=p.LoadBoard(str(D/'ethernet-trial.kicad_pcb'));pos=p.VECTOR2I(p.FromMM(121.5),p.FromMM(74.875));assert any(z.GetNetname()=='GND' and z.GetLayer()==p.In1_Cu and z.HitTestFilledArea(p.In1_Cu,pos) for z in b.Zones())
for f in b.GetFootprints():
 for pad in f.Pads():
  box=pad.GetBoundingBox();box.Inflate(p.FromMM(.25));assert not box.Contains(pos),(f.GetReference(),pad.GetNumber())
d=json.loads((D/'reports/ethernet-trial-drc.json').read_text());assert not d['violations'] and not d['unconnected_items'];backup=D/'before-rx-termination-cluster.kicad_pcb';assert not backup.exists();shutil.copy2(D/'PoE-Speaker-RevE.kicad_pcb',backup);shutil.copy2(D/'ethernet-trial.kicad_pcb',D/'PoE-Speaker-RevE.kicad_pcb');f=E/'revision-e-design.json';m=json.loads(f.read_text());placements=[('R104',119.5,71.6622,0),('R105',120.5,69.2,270),('C102',120.5,74.1,270)]
for ref,x,y,a in placements:m['components'][ref].update(position=[x,y],angle=a,side='Bottom')
f.write_text(json.dumps(m,indent=2)+'\n');(D/'reports/rx-termination-placement.json').write_text(json.dumps({'status':'accepted','placements':[{'reference':r,'position_mm':[x,y],'angle':a,'side':'Bottom'} for r,x,y,a in placements],'ground_via_position_mm':[121.5,74.875],'ground_via_copper_drill_mm':[.6,.3],'ground_center_contacts_filled_plane':True,'obsolete_spur_items_removed':12,'drc_findings':0,'unconnected_items':0,'limits':'Reduces termination branches; does not qualify pair coupling, impedance or length matching. Underside assembly required.'},indent=2))
with (E/'REVE-TRUNK-ROUTING.md').open('a',encoding='utf-8') as out:out.write('\n\n## Accepted Ethernet receive termination cluster — 2026-09-14\n\nMoved R104/R105/C102 to B.Cu near U3, coordinates in reports/rx-termination-placement.json. New short B.Cu links use existing RX signal vias. Rebuilt the RX termination common node and added a 0.6/0.3 mm ground via at (121.5,74.875), confirmed in filled In1 GND and outside component pads. Removed twelve DRC-identified obsolete RX spur items, including one obsolete signal via. Final DRC zero, unconnected zero; bottom render visually inspected. Original main saved as before-rx-termination-cluster.kicad_pcb. This reduces excess termination routing; main pair coupling, impedance, layer transitions and skew remain open. Trial uses a copy of the main project/rules. Trial files must stay out of release archives.\n')
f=E/'package_prototype_review.py';s=f.read_text().replace("('before-','power-trial')","('before-','power-trial','ethernet-trial')");s=s.replace('Next: prioritize Ethernet differential routing/stackup', 'Next: continue Ethernet differential routing/stackup. RX termination R104/R105/C102 is now a compact B.Cu cluster near U3, with twelve obsolete spur items removed and a checked local ground via (reports/rx-termination-placement.json). Main pair routing remains unqualified. Prioritize this');f.write_text(s)
